/**
 * CompScan - a tool for estimating the compressibility of a dataset.
 * 
 * Copyright (c) 2016 DeepStorage, LLC (deepstorage.net) and Ramon A. Lovato (ramonalovato.com).
 * 
 * See the file LICENSE for copying permission.
 */
package net.deepstorage.compscan;

import net.deepstorage.compscan.CompScan.Results;

/**
 * Provides interactive console output for CompScan.
 * 
 * @author Ramon A. Lovato
 * @version 1.0
 */
public class ConsoleDisplayThread extends Thread {
	private Results results;
	private String lastString;
	private long startTime;
	private long elapsedTime;
	
	/**
	 * Constructor.
	 * 
	 * @param results Results object for which to display output.
	 */
	public ConsoleDisplayThread(Results results) {
		this.results = results;
		lastString = "";
		startTime = System.currentTimeMillis();
	}

	@Override
	public void run() {
		while (!isInterrupted()) {
			try {
				sleep(1000);
			} catch (InterruptedException e) {
				break;
			}
			elapsedTime = System.currentTimeMillis() - startTime;
			clearLastLine();
			printProgress();
		}
		System.out.println();
	}
	
	/**
	 * Clear the last line of console output generated by this thread.
	 */
	private void clearLastLine() {
		String s = new String(new char[lastString.length()]).replace('\0', '\b');
		System.out.print(s);
	}
	
	/**
	 * Print a progress line.
	 */
	private void printProgress() {
		String s = String.format("Elapsed time: %1$d sec    Files read: %2$d    Megabytes read: %3$.2f",
				elapsedTime / 1000,
				results.get("files read"),
				((float) results.get("bytes read"))/((float) CompScan.ONE_MB));
		lastString = s;
		System.out.print(s);
	}
}
